package_rename_config:
    android:
        app_name: "Restoverse" # (String) The display name of the android app
        package_name: "com.gverse.restoverse" # (String) The package name of the android app
        override_old_package: "com.example.dcresto" # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
        lang: "kotlin" # (Optional) (String) The android development language {kotlin(default) or java}

    ios:
        app_name: "Restoverse" # (String) The display name of the ios app
        bundle_name: "com.gverse" # (String) The bundle name of the ios app
        package_name: "com.gverse.restoverse" # (String) The product bundle identifier of the ios app
